var classCompanyData = [
	[{
		"name": "科大讯飞股份有限公司",
		"companyid": 47
	}, {
		"name": "北京延龙博阳科贸有限公司",
		"companyid": 63
	}, {
		"name": "天津光电安辰信息技术股份有限公司",
		"companyid": 93
	}, {
		"name": "北京中航安通科技有限公司",
		"companyid": 96
	}, {
		"name": "智器云南京信息科技有限公司",
		"companyid": 117
	}, {
		"name": "深圳市普特斯科技有限公司",
		"companyid": 121
	}, {
		"name": "芜湖市皖江光电仪器有限公司",
		"companyid": 134
	}, {
		"name": "北京和为永泰科技有限公司",
		"companyid": 141
	}, {
		"name": "杭州海康威视系统技术有限公司",
		"companyid": 146
	}, {
		"name": "天津天地伟业数码科技有限公司",
		"companyid": 151
	}, {
		"name": "同方赛威讯信息技术有限公司",
		"companyid": 165
	}, {
		"name": "深信服科技股份有限公司",
		"companyid": 169
	}, {
		"name": "北京鼎盾信息科技有限公司",
		"companyid": 178
	}, {
		"name": "广州宝镜智能科技有限公司",
		"companyid": 180
	}, {
		"name": "苏州科达科技股份有限公司",
		"companyid": 193
	}, {
		"name": "太阳驹（北京）科技发展有限公司",
		"companyid": 196
	}, {
		"name": "四川效率源信息安全技术股份有限公司",
		"companyid": 198
	}, {
		"name": "颐信科技有限公司",
		"companyid": 199
	}, {
		"name": "浪潮集团有限公司",
		"companyid": 201
	}, {
		"name": "北京宝捷拿科技发展有限公司",
		"companyid": 207
	}, {
		"name": "成都卫士通信息产业股份有限公司",
		"companyid": 211
	}, {
		"name": "山西中网信息产业股份有限公司",
		"companyid": 214
	}, {
		"name": "北京鼎电全安警用装备器材有限公司",
		"companyid": 215
	}, {
		"name": "浙江大华技术股份有限公司",
		"companyid": 258
	}, {
		"name": "深圳市亚略特生物识别科技有限公司",
		"companyid": 261
	}, {
		"name": "北京捷通华声科技股份有限公司",
		"companyid": 270
	}, {
		"name": "北京多维视通技术有限公司",
		"companyid": 276
	}, {
		"name": "同方威视技术股份有限公司",
		"companyid": 277
	}, {
		"name": "北京贞和科技有限公司",
		"companyid": 286
	}, {
		"name": "苏州智铸通信科技股份有限公司",
		"companyid": 296
	}, {
		"name": "北京东方通科技股份有限公司",
		"companyid": 301
	}, {
		"name": "司伯睿（北京）移动数据技术有限公司",
		"companyid": 314
	}, {
		"name": "杭州荣安科技有限公司",
		"companyid": 317
	}, {
		"name": "苏州舒尔贸易有限公司",
		"companyid": 338
	}, {
		"name": "湖南麒麟信安科技有限公司",
		"companyid": 341
	}, {
		"name": "华锐视通（北京）科技有限公司",
		"companyid": 343
	}, {
		"name": "中创恩（天津）科技有限公司",
		"companyid": 347
	}, {
		"name": "中兴通讯股份有限公司",
		"companyid": 352
	}, {
		"name": "北京国双科技有限公司",
		"companyid": 354
	}, {
		"name": "北京淳中科技股份有限公司",
		"companyid": 358
	}, {
		"name": "北京颐正海纳科技有限公司",
		"companyid": 360
	}, {
		"name": "北京信任度科技有限公司",
		"companyid": 362
	}, {
		"name": "山东灵创信息技术有限公司",
		"companyid": 364
	}, {
		"name": "北京思博纳科技发展有限公司",
		"companyid": 365
	}, {
		"name": "江苏博智软件科技股份有限公司",
		"companyid": 367
	}, {
		"name": "北京握奇数据股份有限公司",
		"companyid": 369
	}, {
		"name": "无锡日联科技股份有限公司",
		"companyid": 370
	}, {
		"name": "上海天岸电子科技有限公司",
		"companyid": 371
	}, {
		"name": "山东三木众合信息科技股份有限公司",
		"companyid": 373
	}],
	[{
		"name": "北京市汉龙实业有限公司",
		"companyid": 60
	}, {
		"name": "嘉兴东臣信息科技有限公司",
		"companyid": 81
	}, {
		"name": "北京圆创软件有限公司",
		"companyid": 91
	}, {
		"name": "安徽启路达光电科技有限公司",
		"companyid": 107
	}, {
		"name": "广州星博科仪有限公司",
		"companyid": 110
	}, {
		"name": "北京同方神火联合科技发展有限公司",
		"companyid": 114
	}, {
		"name": "上海中晶科技有限公司",
		"companyid": 115
	}, {
		"name": "北京千江仪器有限公司",
		"companyid": 116
	}, {
		"name": "大连睿海信息科技有限公司",
		"companyid": 130
	}, {
		"name": "南京安信达信息科技有限公司",
		"companyid": 136
	}, {
		"name": "北京美斯齐文化科技有限公司",
		"companyid": 142
	}, {
		"name": "北京新科永创科技有限公司",
		"companyid": 148
	}, {
		"name": "北京安信荣达科技有限公司",
		"companyid": 150
	}, {
		"name": "北京紫光图文系统有限公司",
		"companyid": 153
	}, {
		"name": "南京名都智能科技有限公司",
		"companyid": 170
	}, {
		"name": "合肥源信智能仪器有限公司",
		"companyid": 184
	}, {
		"name": "北京北大英华科技有限公司",
		"companyid": 202
	}, {
		"name": "杭州席媒科技有限公司",
		"companyid": 204
	}, {
		"name": "兄弟（中国）商业有限公司",
		"companyid": 217
	}, {
		"name": "利盟信息技术（中国）有限公司",
		"companyid": 225
	}, {
		"name": "芜湖市奥尔特光电科技有限公司",
		"companyid": 230
	}, {
		"name": "济南致业电子有点公司",
		"companyid": 233
	}, {
		"name": "佳能（中国）有限公司",
		"companyid": 234
	}, {
		"name": "深圳顺泰伟成科技有限公司",
		"companyid": 237
	}, {
		"name": "北京阳宸电子技术公司",
		"companyid": 241
	}, {
		"name": "北京财富佳美科技有限公司",
		"companyid": 248
	}, {
		"name": "码萨埃比科技（北京）有限公司",
		"companyid": 250
	}, {
		"name": "北京沃尔奔达光电装备有限公司",
		"companyid": 251
	}, {
		"name": "科大乐芮管理（上海）有限公司",
		"companyid": 264
	}, {
		"name": "富士通信息系统（深圳）有限公司",
		"companyid": 267
	}, {
		"name": "北京米奥科技有限公司",
		"companyid": 274
	}, {
		"name": "蓝盾信息安全技术股份有限公司",
		"companyid": 275
	}, {
		"name": "北京亚博通科技发展有限公司",
		"companyid": 278
	}, {
		"name": "山东胜软科技股份有限公司",
		"companyid": 287
	}, {
		"name": "大连成者科技有限公司",
		"companyid": 292
	}, {
		"name": "北京恒安讯佳信息安全技术有限公司",
		"companyid": 297
	}, {
		"name": "杭州永控科技有限公司",
		"companyid": 304
	}, {
		"name": "内蒙古成迈信息科技有限公司",
		"companyid": 315
	}, {
		"name": "北京录典世纪科技有限公司",
		"companyid": 316
	}, {
		"name": "中国缩微系统有限公司",
		"companyid": 318
	}, {
		"name": "广州视臻信息科技有限公司",
		"companyid": 319
	}, {
		"name": "乌鲁木齐新太博软件信息技术有限公司",
		"companyid": 320
	}, {
		"name": "北京科旭威尔科技股份有限公司",
		"companyid": 345
	}, {
		"name": "深圳市台电实业有限公司",
		"companyid": 350
	}, {
		"name": "新要素科技（深圳）有限公司",
		"companyid": 353
	}, {
		"name": "中经名气网络技术（北京）有限公司",
		"companyid": 356
	}, {
		"name": "河南山谷网安科技股份有限公司",
		"companyid": 357
	}, {
		"name": "山东鸿业信息科技有限公司",
		"companyid": 359
	}, {
		"name": "北京维山科技有限公司",
		"companyid": 361
	}, {
		"name": "深圳市神州云海智能科技有限公司",
		"companyid": 363
	}, {
		"name": "松下电器（中国）有限公司",
		"companyid": 366
	}, {
		"name": "北京影研创新科技发展有限公司",
		"companyid": 368
	}, {
		"name": "杭州艾米机器人有限公司",
		"companyid": 372
	}, {
		"name": "深圳市爱思拓信息储存技术有限公司",
		"companyid": 374
	}, {
		"name": "北京优利绚彩科技发展有限公司",
		"companyid": 375
	}, {
		"name": "北京同方光盘股份有限公司",
		"companyid": 376
	}, {
		"name": "北京融通新风洁净技术有限公司",
		"companyid": 377
	}],
	[{
		"name": "北京瑞天平安信息技术有限公司",
		"companyid": 79
	}, {
		"name": "北京联创拓值科技有限公司",
		"companyid": 144
	}, {
		"name": "杭州平航科技有限公司",
		"companyid": 152
	}, {
		"name": "北京盛宏图科技发展有限公司",
		"companyid": 168
	}, {
		"name": "北京瑞源文德科技有限公司",
		"companyid": 200
	}, {
		"name": "北京融安特智能科技股份有限公司",
		"companyid": 281
	}, {
		"name": "成都科来软件有限公司",
		"companyid": 293
	}, {
		"name": "北京迪士比科技有限公司",
		"companyid": 320
	}, {
		"name": "河南金明源信息技术有限公司",
		"companyid": 322
	}, {
		"name": "蓝信移动（北京）科技有限公司",
		"companyid": 323
	}, {
		"name": "西安萨默尔机器人科技有限公司",
		"companyid": 324
	}, {
		"name": "北京壹人壹本信息科技有限公司",
		"companyid": 325
	}, {
		"name": "北京华软金盾软件有限公司",
		"companyid": 326
	}, {
		"name": "苏州凌旭信息科技有限公司",
		"companyid": 327
	}, {
		"name": "福建捷宇电脑科技有限公司",
		"companyid": 329
	}, {
		"name": "理想（中国）科学工业有限公司",
		"companyid": 295
	}, {
		"name": "中孚信息股份技术有限公司",
		"companyid": 312
	}, {
		"name": "北京利华瑞特科技有限公司",
		"companyid": 330
	}, {
		"name": "北京赛迪时代信息产业股份有限公司",
		"companyid": 331
	}, {
		"name": "杭州华会通科技股份有限公司",
		"companyid": 333
	}, {
		"name": "合肥视尔信息科技有限公司",
		"companyid": 335
	}, {
		"name": "河北欣诚信息技术有限公司",
		"companyid": 337
	}, {
		"name": "河南华正通信息技术有限公司",
		"companyid": 339
	}, {
		"name": "成都立鑫新技术科技有限公司",
		"companyid": 344
	}],
	[{
		"name": "联想长风科技（北京）有限公司",
		"companyid": 313
	}, {
		"name": "山东闻远通信技术有限公司",
		"companyid": 84
	}, {
		"name": "中标软件有限公司",
		"companyid": 108
	}, {
		"name": "上海数腾软件科技股份有限公司",
		"companyid": 239
	}, {
		"name": "北京盈诚科技有限公司",
		"companyid": 310
	}, {
		"name": "北京法意科技有限公司",
		"companyid": 336
	}, {
		"name": "北京易恒网络科技发展有限公司",
		"companyid": 340
	}, {
		"name": "北京理工雷科电子信息技术有限公司",
		"companyid": 342
	}, {
		"name": "武汉华工安鼎信息技术有限责任公司",
		"companyid": 346
	},  {
		"name": "上海英方软件股份有限公司",
		"companyid": 351
	}]
]